#!bash
python3 finetune_deepseekcoder2.py \
    --model_name_or_path deepseek-ai/deepseek-coder-1.3b-instruct \
    --data_path ./train_data.json \
    --output_dir ./LoRa \
    --num_train_epochs 5 \
    --per_device_train_batch_size 16 \
    --gradient_accumulation_steps 4 \
    --save_strategy "steps" \
    --save_steps 50 \
    --learning_rate 3e-4 \
    --warmup_steps 50 \
    --logging_steps 10 \
	--weight_decay 0.001 \
    --max_grad_norm 0.8 \
	--lr_scheduler_type "cosine" \
    --gradient_checkpointing True \
    --report_to "tensorboard" \
    --bf16 True \
    --model_max_length 1024 \
	--save_only_model True